version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - student_registration_app_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: student_registration
      POSTGRES_USER: student_registration
      POSTGRES_PASSWORD: student_registration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - student_registration_app_network

volumes:
  postgres_data:
networks:
  student_registration_app_network:
